apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    jsonData:
      timeInterval: '15s'
      queryTimeout: '60s'
      httpMethod: 'POST'
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: tempo
          url: $${__value.raw}
    editable: false
    version: 1

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    jsonData:
      timeInterval: '15s'
      maxLines: 1000
    editable: false
    version: 1

  - name: Postgres
    type: postgres
    access: proxy
    orgId: 1
    url: ${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}
    database: ${POSTGRES_DB:-postgres}
    user: ${POSTGRES_USER:-postgres}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-postgres}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 3
      connMaxLifetime: 14400
      postgresVersion: 1400
    editable: false
    version: 1