server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: terrabuild
        __path__: /var/log/*log

  - job_name: containers
    static_configs:
    - targets:
        - localhost
      labels:
        job: terrabuild-containers
        __path__: /var/lib/docker/containers/*/*.log

  - job_name: nodejs-app
    static_configs:
    - targets:
        - localhost
      labels:
        job: terrabuild-app
        __path__: /app/logs/**/*.log