global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@terrafusion.example.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-email'
  routes:
    - match:
        severity: critical
      receiver: 'team-pager'
      continue: true
    - match:
        service: database
      receiver: 'db-team'
      continue: true
    - match:
        service: api
      receiver: 'api-team'
      continue: true
    - match:
        service: agents
      receiver: 'ai-team'
      continue: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

receivers:
  - name: 'team-email'
    email_configs:
      - to: 'team@terrafusion.example.com'
        send_resolved: true
  
  - name: 'team-pager'
    pagerduty_configs:
      - service_key: '<PAGERDUTY_SERVICE_KEY>'
        send_resolved: true
  
  - name: 'db-team'
    email_configs:
      - to: 'db-team@terrafusion.example.com'
        send_resolved: true

  - name: 'api-team'
    email_configs:
      - to: 'api-team@terrafusion.example.com'
        send_resolved: true

  - name: 'ai-team'
    email_configs:
      - to: 'ai-team@terrafusion.example.com'
        send_resolved: true