groups:
  - name: terrafusion_alerts
    rules:
      # API Availability
      - alert: TerraFusionAPIDown
        expr: up{job="terrafusion"} == 0
        for: 1m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "TerraFusion API is down"
          description: "TerraFusion API has been down for more than 1 minute."
          runbook_url: "https://wiki.terrafusion.example/ops/runbooks/api-down"

      # Request Errors
      - alert: HighAPIErrorRate
        expr: sum(rate(http_requests_total{job="terrafusion",status=~"5.."}[5m])) / sum(rate(http_requests_total{job="terrafusion"}[5m])) > 0.05
        for: 2m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High API error rate"
          description: "Error rate is above 5% ({{ $value | printf \"%.2f\" }})"
          runbook_url: "https://wiki.terrafusion.example/ops/runbooks/high-error-rate"

      # Latency
      - alert: APIHighLatency
        expr: http_request_duration_seconds{job="terrafusion",quantile="0.95"} > 2
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High API latency"
          description: "95th percentile request latency is above 2 seconds for path {{ $labels.path }}"
          runbook_url: "https://wiki.terrafusion.example/ops/runbooks/high-latency"

      # System Resources
      - alert: APIHighCPUUsage
        expr: sum(rate(process_cpu_seconds_total{job="terrafusion"}[5m])) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High CPU usage in API"
          description: "API CPU usage is above 80% for more than 5 minutes"
          runbook_url: "https://wiki.terrafusion.example/ops/runbooks/high-cpu"

      - alert: APIHighMemoryUsage
        expr: process_resident_memory_bytes{job="terrafusion"} > 1.5e+9
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High memory usage in API"
          description: "API memory usage is above 1.5GB for more than 5 minutes"
          runbook_url: "https://wiki.terrafusion.example/ops/runbooks/high-memory"

      # Database
      - alert: PostgreSQLDown
        expr: up{job="postgresql"} == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL exporter has been down for more than 1 minute"
          runbook_url: "https://wiki.terrafusion.example/ops/runbooks/postgresql-down"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_activity_count{datname="terrafusion"} > 50
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "High number of PostgreSQL connections"
          description: "More than 50 PostgreSQL connections for more than 5 minutes"
          runbook_url: "https://wiki.terrafusion.example/ops/runbooks/postgresql-connections"
      
      # Agent Monitoring
      - alert: AgentDown
        expr: up{job="terrafusion-agents"} == 0
        for: 2m
        labels:
          severity: warning
          service: agents
        annotations:
          summary: "TerraFusion agent is down"
          description: "Agent {{ $labels.instance }} has been down for more than 2 minutes"
          runbook_url: "https://wiki.terrafusion.example/ops/runbooks/agent-down"