server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            tag: tag
      - json:
          expressions:
            tag: attrs.tag
          source: attrs
      - regex:
          expression: (?P<container_name>([a-zA-Z0-9][a-zA-Z0-9_.-]+))
          source: tag
      - labels:
          tag:
          stream:
          container_name:

  - job_name: terrafusion_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: terrafusion
          __path__: /var/log/terrafusion/*.log
    pipeline_stages:
      - regex:
          expression: '^\[(?P<timestamp>.*?)\]\s+(?P<level>.*?)\s+(?P<message>.*?)$'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: '2006-01-02T15:04:05.999999999Z07:00'