global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'pagerduty-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-notifications'
      continue: true
    - match:
        severity: info
      receiver: 'email-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#terrafusion-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        title_link: 'https://grafana.benton-county.example.com/d/terrafusion'
        text: >-
          {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            *Severity:* {{ .Labels.severity }}
            *Environment:* {{ .Labels.environment }}
            *Service:* {{ .Labels.service }}
          {{ end }}
        icon_url: 'https://avatars0.githubusercontent.com/u/3380462'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'https://grafana.benton-county.example.com/d/terrafusion'
          - type: button
            text: 'View in Prometheus'
            url: 'https://prometheus.benton-county.example.com/alerts'
  
  - name: 'email-notifications'
    email_configs:
      - to: 'infrastructure@benton-county.example.com'
        from: 'prometheus@benton-county.example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'prometheus@benton-county.example.com'
        auth_identity: 'prometheus@benton-county.example.com'
        auth_password: '{{ .Values.alertmanager.smtp_auth_password }}'
        send_resolved: true
  
  - name: 'pagerduty-critical'
    pagerduty_configs:
      - service_key: '{{ .Values.alertmanager.pagerduty_key }}'
        send_resolved: true
        description: '{{ template "pagerduty.default.description" . }}'
        client: 'Prometheus'
        client_url: 'https://prometheus.benton-county.example.com'
        details:
          firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
          resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
          num_firing: '{{ .Alerts.Firing | len }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']