groups:
  - name: terrabuild_alerts
    rules:
      - alert: HighMemoryUsage
        expr: app_memory_usage_bytes{type="heapUsed"} / app_memory_usage_bytes{type="heapTotal"} > 0.85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "TerraBuild application is using more than 85% of available heap memory for more than 2 minutes."

      - alert: DatabaseConnectionDown
        expr: app_database_connected == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Database connection lost"
          description: "TerraBuild application has lost connection to the database."

      - alert: AgentUnhealthy
        expr: app_agent_status{agent=~".+"} == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "AI Agent unhealthy"
          description: "TerraBuild AI Agent {{ $labels.agent }} is reporting unhealthy status."

      - alert: ApplicationDown
        expr: up{job="terrabuild"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Application is down"
          description: "TerraBuild application is not responding to metrics scrape."