global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'terrafusion'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['api:5000']
        labels:
          service: 'api'
          environment: '${ENV}'

  - job_name: 'terrafusion-agents'
    metrics_path: '/metrics'
    scheme: 'http'
    dns_sd_configs:
      - names:
          - 'tasks.agent'
        type: 'A'
        port: 8080
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: agent_service
      - source_labels: [__meta_dns_srv_record_target]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        regex: '([^:]+)(?::\\d+)?'
        replacement: '${1}:8080'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          environment: '${ENV}'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'
          environment: '${ENV}'