name: CI Pipeline

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for CodeQL and SonarCloud analysis
      
      # Initialize CodeQL Analysis for security scanning
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint || npm run check
      
      # Dependency vulnerability scanning
      - name: Dependency scanning
        run: npx audit-ci --moderate
        continue-on-error: true
      
      # Run static code analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      
      # Generate code coverage report
      - name: Run unit tests with coverage
        run: npm test -- --coverage
        env:
          NODE_ENV: test
      
      # Upload coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
        if: success()

  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    needs: code-quality
    
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
      
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: bcbs
          POSTGRES_PASSWORD: bcbs
          POSTGRES_DB: bcbs_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Scan Docker image for vulnerabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker images
        run: docker-compose build
      
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'bcbs-app_web:latest'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
      
      - name: Start services
        run: docker-compose up -d
      
      - name: Wait for services to be ready
        run: sleep 15
      
      - name: Smoke test
        run: |
          # Check if the server is running
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:5000/ || exit 1
          
          # Run smoke tests if available
          if [ -f "npm run smoke-test" ]; then
            npm run smoke-test
          else
            echo "No smoke tests defined, skipping"
          fi
          
          # Capture application metrics during test for performance baseline
          echo "Capturing application metrics..."
          curl --retry 3 --retry-delay 2 --retry-connrefused http://localhost:5000/health > health_metrics.json || echo "Health endpoint not available"
      
      - name: Tear down
        run: docker-compose down
        if: always()
      
      - name: Build application
        run: npm run build
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      
      - name: Upload metrics
        uses: actions/upload-artifact@v3
        with:
          name: application-metrics
          path: health_metrics.json
        if: success()
      
      - name: Upload logs on failure
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            logs/
            npm-debug.log*
            yarn-debug.log*
            yarn-error.log*
        if: failure()

  pipeline-metrics:
    name: Pipeline Metrics
    runs-on: ubuntu-latest
    needs: [code-quality, test-and-build]
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Generate pipeline metrics
        run: |
          echo "Generating CI/CD pipeline metrics..."
          echo "{\"run_id\": \"$GITHUB_RUN_ID\", \"workflow\": \"$GITHUB_WORKFLOW\", \"status\": \"${{ job.status }}\", \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"}" > pipeline_metrics.json
      
      - name: Upload pipeline metrics
        uses: actions/upload-artifact@v3
        with:
          name: pipeline-metrics
          path: pipeline_metrics.json